esphome:
  name: snapcast_dac

esp32:
  board: esp32dev
  partitions: partitions.csv
  framework:
    type: esp-idf

external_components:
  - source: components
    components: [ snapclient, i2s_audio ]

network:
  enable_ipv6: true

wifi:
  ssid: !secret ssid
  password: !secret password

# enable api for connecting to home assistant
#api:

ota:
  - platform: esphome

# Enable logging
logger:
  level: debug
  logs:
    wifi: info
    api: info
    mdns: info

i2s_audio:
  i2s_bclk_pin: 23
  i2s_lrclk_pin: 13

audio_dac:
  - platform: es8311
    id: dac

i2c:
  sda: 1
  scl: 2

snapclient:
  hostname: !secret snap_host
  name: esphome-test
  i2s_dout_pin: 14
  audio_dac: dac
